nom: "Loz Town Patrol"
description: "Association sound system & culture dub — Lausanne, Suisse"
url: "https://www.loztownpatrol.ch"
annee_courante: 2025
reseaux:
  facebook: "#"
  instagram: "#"
  soundcloud: "#"
  youtube: "#"
